<?php

if ( function_exists( 'acf_add_local_field_group' ) ) {

	global $wp_rewrite;

	$slug_prepend = trim( $wp_rewrite->front, "/" );

	// acpt-basic main
	acf_add_local_field_group( array(
		'key'                   => 'group_576c917f2166e',
		'title'                 => 'acpt-basic',
		'fields'                => array(
			array(
				'key'               => 'field_576c9220dcc28',
				'label'             => 'Plural Name',
				'name'              => 'acpt_plural_name',
				'type'              => 'text',
				'instructions'      => 'General name for the post type. Default is Posts/Pages',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576c92a8dcc29',
				'label'             => 'Singular Name',
				'name'              => 'acpt_singular_name',
				'type'              => 'text',
				'instructions'      => 'Name for one object of this post type. Default is Post/Page',
				'required'          => 1,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576ca22e38fa5',
				'label'             => 'Description',
				'name'              => 'acpt_description',
				'type'              => 'textarea',
				'instructions'      => 'A short descriptive summary of what the post type is.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'maxlength'         => '',
				'rows'              => 3,
				'new_lines'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576caf4c3f8e8',
				'label'             => 'Hierarchical',
				'name'              => 'acpt_hierarchical',
				'type'              => 'true_false',
				'instructions'      => 'Page attributes must be included in supported functionality to show the parent select box on the editor page.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether the post type allows a parent to be specified.',
				'default_value'     => 0,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'acpt_content_type',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

	// acpt-advanced main
	acf_add_local_field_group( array(
		'key'                   => 'group_576f06fc7f2f2',
		'title'                 => 'acpt-advanced',
		'fields'                => array_filter( array(
			array(
				'key'               => 'field_576f06fc8303d',
				'label'             => 'Advanced',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 1,
			),
			array(
				'key'               => 'field_576f06fc83060',
				'label'             => 'Public',
				'name'              => 'acpt_public',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Controls how the type is visible to authors and readers.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc83119',
				'label'             => 'Show in Admin UI',
				'name'              => 'acpt_show_ui',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to generate a default UI for managing this post type in the admin.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc59164',
				'label'             => 'Rewrite URL',
				'name'              => 'acpt_rewrite',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to trigger the handling of rewrites for this post type.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc22742',
				'label'             => 'Has Archive',
				'name'              => 'acpt_has_archive',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether post type archives are enabled.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc32742',
				'label'             => 'Show in Navigation Menus',
				'name'              => 'acpt_show_in_nav_menus',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether post type is available for selection in navigation menus..',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc83082',
				'label'             => 'Exclude from Search',
				'name'              => 'acpt_exclude_from_search',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to exclude posts with this post type from front end search results.',
				'default_value'     => 0,
			),
			array(
				'key'               => 'field_576f06fc830ae',
				'label'             => 'Publicly Queryable',
				'name'              => 'acpt_publicly_queryable',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether queries can be performed on the front end.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc830bb',
				'label'             => 'Can Export',
				'name'              => 'acpt_can_export',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether this post type can be exported.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc830c9',
				'label'             => 'Show in REST API',
				'name'              => 'acpt_show_in_rest',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to expose this post type in the REST API.',
				'default_value'     => 0,
			),
			array(
				'key'               => 'field_576f06fc83106',
				'label'             => 'Admin',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc83119',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83127',
				'label'             => 'Show in Admin Menu',
				'name'              => 'acpt_show_in_menu',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to show the post type in the admin menu.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc23127',
				'label'             => 'Show under a Parent',
				'name'              => 'acpt_show_under_a_parent',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => 'child-field',
					'id'    => '',
				),
				'message'           => 'Whether to show the post type under a parent.',
				'default_value'     => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc83127',
							'operator' => '==',
							'value'    => '1',
						),
					),
				)
			),
			array(
				'key'               => 'field_576f06fc83135',
				'label'             => 'Under Parent',
				'name'              => 'acpt_show_under_parent',
				'type'              => 'select',
				'instructions'      => 'The post type will be placed as a sub menu of the selected page.',
				'required'          => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => 'child-field',
					'id'    => '',
				),
				'default_value'     => '',
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc23127',
							'operator' => '==',
							'value'    => '1',
						),
					),
				)
			),
			array(
				'key'               => 'field_576f06fc83150',
				'label'             => 'Menu Position',
				'name'              => 'acpt_menu_position',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc23127',
							'operator' => '!=',
							'value'    => '1',
						),
						array(
							'field'    => 'field_576f06fc83127',
							'operator' => '==',
							'value'    => '1',
						),
					)
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					- 1 => 'Custom Position',
					5   => '5 - below Posts',
					10  => '10 - below Media',
					15  => '15 - below Links',
					20  => '20 - below Pages',
					25  => '25 - below comments',
					60  => '60 - below first separator',
					65  => '65 - below Plugins',
					70  => '70 - below Users',
					75  => '75 - below Tools',
					80  => '80 - below Settings',
					100 => '100 - below second separator',
				),
				'default_value'     => array(
					0 => 5,
				),
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 0,
				'ajax'              => 0,
				'placeholder'       => '',
				'disabled'          => 0,
				'readonly'          => 0,
			),
			array(
				'key'               => 'field_576f06fc8315f',
				'label'             => 'Custom Position',
				'name'              => 'acpt_menu_position_custom',
				'type'              => 'number',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc83150',
							'operator' => '==',
							'value'    => '-1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => 'child-field hide-title',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'min'               => '',
				'max'               => '',
				'step'              => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc8316d',
				'label'             => 'Menu Icon',
				'name'              => 'acpt_menu_icon',
				'type'              => 'select',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc23127',
							'operator' => '!=',
							'value'    => '1',
						),
						array(
							'field'    => 'field_576f06fc83127',
							'operator' => '==',
							'value'    => '1',
						),
					)
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(),
				'default_value'     => array(),
				'allow_null'        => 0,
				'multiple'          => 0,
				'ui'                => 0,
				'ajax'              => 0,
				'placeholder'       => '',
				'disabled'          => 0,
				'readonly'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83142',
				'label'             => 'Show in Admin Bar',
				'name'              => 'acpt_show_in_admin_bar',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to make this post type available in the WordPress admin bar.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc8317a',
				'label'             => 'Labels',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_5774abc0a9dfc',
				'label'             => 'Create Labels Automatically',
				'name'              => 'acpt_auto_generate_labels',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether to automatically create the labels.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc83188',
				'label'             => 'Add New',
				'name'              => 'acpt_label_add_new',
				'type'              => 'text',
				'instructions'      => 'the add new text. The default is "Add New" for both hierarchical and non-hierarchical post types.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Add New',
				'placeholder'       => 'Add New',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83195',
				'label'             => 'Add New Item',
				'name'              => 'acpt_label_add_new_item',
				'type'              => 'text',
				'instructions'      => 'Default is Add New Post/Add New Page.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831a3',
				'label'             => 'Edit Item',
				'name'              => 'acpt_label_edit_item',
				'type'              => 'text',
				'instructions'      => 'Default is Edit Post/Edit Page.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831b0',
				'label'             => 'New Item',
				'name'              => 'acpt_label_new_item',
				'type'              => 'text',
				'instructions'      => 'Default is New Post/New Page.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831be',
				'label'             => 'View Item',
				'name'              => 'acpt_label_view_item',
				'type'              => 'text',
				'instructions'      => 'Default is View Post/View Page.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831cb',
				'label'             => 'Search Items',
				'name'              => 'acpt_label_search_items',
				'type'              => 'text',
				'instructions'      => 'Default is Search Posts/Search Pages.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831d9',
				'label'             => 'Not Found',
				'name'              => 'acpt_label_not_found',
				'type'              => 'text',
				'instructions'      => 'Default is No posts found/No pages found.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831e6',
				'label'             => 'Not Found in Trash',
				'name'              => 'acpt_label_not_found_in_trash',
				'type'              => 'text',
				'instructions'      => 'Default is No posts found in Trash/No pages found in Trash.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc831f3',
				'label'             => 'Parent Item Colon',
				'name'              => 'acpt_label_parent_item_colon',
				'type'              => 'text',
				'instructions'      => 'This string isn\'t used on non-hierarchical types. In hierarchical ones the default is \'Parent Page:\'.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83200',
				'label'             => 'All Items',
				'name'              => 'acpt_label_all_items',
				'type'              => 'text',
				'instructions'      => 'Text for the submenu. Default is All Posts/All Pages.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc8320d',
				'label'             => 'Archives',
				'name'              => 'acpt_label_archives',
				'type'              => 'text',
				'instructions'      => 'Text for use with archives in nav menus. Default is Post Archives/Page Archives.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc8321b',
				'label'             => /** @lang text */'Insert into Item',
				'name'              => 'acpt_label_insert_into_item',
				'type'              => 'text',
				'instructions'      => 'Text for the media frame button. Default is Insert into post/Insert into page.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83228',
				'label'             => 'Uploaded to This Item',
				'name'              => 'acpt_label_uploaded_to_this_item',
				'type'              => 'text',
				'instructions'      => 'Text for the media frame filter. Default is Uploaded to this post/Uploaded to this page.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83235',
				'label'             => 'Featured Image',
				'name'              => 'acpt_label_featured_image',
				'type'              => 'text',
				'instructions'      => 'Default is Featured Image.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Featured Image',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83242',
				'label'             => 'Set Featured Image',
				'name'              => 'acpt_label_set_featured_image',
				'type'              => 'text',
				'instructions'      => 'Default is Set featured image.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Set featured image.',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83250',
				'label'             => 'Remove Featured Image',
				'name'              => 'acpt_label_remove_featured_image',
				'type'              => 'text',
				'instructions'      => 'Default is Remove featured image.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Remove featured image.',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc8325d',
				'label'             => 'Use Featured Image',
				'name'              => 'acpt_label_use_featured_image',
				'type'              => 'text',
				'instructions'      => 'Default is Use as featured image.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => 'Use as featured image.',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc8326a',
				'label'             => 'Menu Name',
				'name'              => 'acpt_label_menu_name',
				'type'              => 'text',
				'instructions'      => 'Default is the same as `Plural Name`.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83279',
				'label'             => 'Filter Items List',
				'name'              => 'acpt_label_filter_items_list',
				'type'              => 'text',
				'instructions'      => 'Text for the table views hidden heading.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83286',
				'label'             => 'Items List Navigation',
				'name'              => 'acpt_label_items_list_navigation',
				'type'              => 'text',
				'instructions'      => 'Text for the table pagination hidden heading.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc83293',
				'label'             => 'Items List',
				'name'              => 'acpt_label_items_list',
				'type'              => 'text',
				'instructions'      => 'Text for the table hidden heading.
',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc832a0',
				'label'             => 'Name Admin Bar',
				'name'              => 'acpt_label_name_admin_bar',
				'type'              => 'text',
				'instructions'      => 'Text for use in New in Admin menu bar. Default is the same as `Singular Name`.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_577817c143802',
				'label'             => 'Rewrite',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc59164',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			$slug_prepend ? array(
				'key'               => 'field_57781a8d43805',
				'label'             => 'Slug',
				'name'              => 'acpt_rewrite_with_front',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Should the permalink structure be prepended with the front base.',
				'default_value'     => 0,
			) : null,
			array(
				'key'               => 'field_577819f443804',
				'label'             => $slug_prepend ? 'Slug / Hidden' : 'Slug',
				'name'              => 'acpt_rewrite_slug',
				'type'              => 'text',
				'instructions'      => 'Customize the permalink structure slug. Defaults to a URL friendly version of the singular name value. Should be translatable.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => $slug_prepend ? 'child-field hide-title' : '',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => $slug_prepend ? $slug_prepend : '/',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_57781b3343807',
				'label'             => 'Feeds',
				'name'              => 'acpt_rewrite_feeds',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether a feed permalink structure should be built for this post type. Defaults to the \'Has Archive\' value.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_5778210043808',
				'label'             => 'Pages',
				'name'              => 'acpt_rewrite_pages',
				'type'              => 'true_false',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'message'           => 'Whether the permalink structure should provide for pagination.',
				'default_value'     => 1,
			),
			array(
				'key'               => 'field_576f06fc73106',
				'label'             => 'REST API',
				'name'              => '',
				'type'              => 'tab',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc830c9',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'placement'         => 'top',
				'endpoint'          => 0,
			),
			array(
				'key'               => 'field_576f06fc830d6',
				'label'             => 'Base Slug',
				'name'              => 'acpt_rest_base_slug',
				'type'              => 'text',
				'instructions'      => 'The base slug that this post type will use when accessed using the REST API.',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => 'child-field',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
			array(
				'key'               => 'field_576f06fc830e4',
				'label'             => 'Controller Class',
				'name'              => 'acpt_rest_controller_class',
				'type'              => 'text',
				'instructions'      => 'An optional custom controller to use instead of WP_REST_Posts_Controller. Must be a subclass of WP_REST_Controller.',
				'required'          => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_576f06fc830c9',
							'operator' => '==',
							'value'    => '1',
						),
					),
				),
				'wrapper'           => array(
					'width' => '',
					'class' => 'child-field',
					'id'    => '',
				),
				'default_value'     => '',
				'placeholder'       => '',
				'prepend'           => '',
				'append'            => '',
				'maxlength'         => '',
				'readonly'          => 0,
				'disabled'          => 0,
			),
		) ),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'acpt_content_type',
				),
			),
		),
		'menu_order'            => 100,
		'position'              => 'normal',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
	) );

	// acpt-supports side
	acf_add_local_field_group( array(
		'key'                   => 'group_576f06faa6677',
		'title'                 => 'acpt-supports',
		'fields'                => array(
			array(
				'key'               => 'field_576f06faaa174',
				'label'             => 'Supported Functionality',
				'name'              => 'acpt_supports',
				'type'              => 'checkbox',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'title'           => 'Title',
					'editor'          => 'Content Editor',
					'author'          => 'Author',
					'thumbnail'       => 'Thumbnail',
					'excerpt'         => 'Excerpt',
					'trackbacks'      => 'Trackbacks',
					'custom-fields'   => 'Custom Fields',
					'comments'        => 'Comments',
					'revisions'       => 'Revisions',
					'page-attributes' => 'Page Attributes',
					'post-formats'    => 'Post Formats',
				),
				'default_value'     => array(
					0 => 'title',
					1 => 'editor',
				),
				'layout'            => 'vertical',
				'toggle'            => 0,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'acpt_content_type',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
		'local'                 => 'php',
	) );

	// acpt-taxonomies side
	acf_add_local_field_group( array(
		'key'                   => 'group_576f1c751aed7',
		'title'                 => 'acpt-taxonomies',
		'fields'                => array(
			array(
				'key'               => 'field_576f1c751d202',
				'label'             => 'Taxonomies',
				'name'              => 'acpt_taxonomies',
				'type'              => 'checkbox',
				'instructions'      => '',
				'required'          => 0,
				'conditional_logic' => 0,
				'wrapper'           => array(
					'width' => '',
					'class' => '',
					'id'    => '',
				),
				'choices'           => array(
					'category' => 'Categories',
					'post_tag' => 'Tags',
				),
				'default_value'     => array(),
				'layout'            => 'vertical',
				'toggle'            => 0,
			),
		),
		'location'              => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'acpt_content_type',
				),
			),
		),
		'menu_order'            => 0,
		'position'              => 'side',
		'style'                 => 'default',
		'label_placement'       => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen'        => '',
		'active'                => 1,
		'description'           => '',
		'local'                 => 'php',
	) );

}